(cl:defpackage simulator-srv
  (:use )
  (:export
   "SIMULATOR_BASE"
   "<SIMULATOR_BASE-REQUEST>"
   "SIMULATOR_BASE-REQUEST"
   "<SIMULATOR_BASE-RESPONSE>"
   "SIMULATOR_BASE-RESPONSE"
   "SIMULATOR_PARAMETERS"
   "<SIMULATOR_PARAMETERS-REQUEST>"
   "SIMULATOR_PARAMETERS-REQUEST"
   "<SIMULATOR_PARAMETERS-RESPONSE>"
   "SIMULATOR_PARAMETERS-RESPONSE"
   "SIMULATOR_ROBOT_STEP"
   "<SIMULATOR_ROBOT_STEP-REQUEST>"
   "SIMULATOR_ROBOT_STEP-REQUEST"
   "<SIMULATOR_ROBOT_STEP-RESPONSE>"
   "SIMULATOR_ROBOT_STEP-RESPONSE"
  ))

