(cl:in-package simulator-srv)
(cl:export '(REQUEST-VAL
          REQUEST
          ROBOT_X-VAL
          ROBOT_X
          ROBOT_Y-VAL
          ROBOT_Y
          ROBOT_THETA-VAL
          ROBOT_THETA
          ROBOT_RADIO-VAL
          ROBOT_RADIO
          ROBOT_MAX_ADVANCE-VAL
          ROBOT_MAX_ADVANCE
          ROBOT_TURN_ANGLE-VAL
          ROBOT_TURN_ANGLE
          LASER_NUM_SENSORS-VAL
          LASER_NUM_SENSORS
          LASER_ORIGIN-VAL
          LASER_ORIGIN
          LASER_RANGE-VAL
          LASER_RANGE
          LASER_VALUE-VAL
          LASER_VALUE
          WORLD_NAME-VAL
          WORLD_NAME
          NOISE-VAL
          NOISE
          RUN-VAL
          RUN
          LIGHT_X-VAL
          LIGHT_X
          LIGHT_Y-VAL
          LIGHT_Y
          BEHAVIOR-VAL
          BEHAVIOR
          STEPS-VAL
          STEPS
))