(cl:defpackage clips_ros-srv
  (:use )
  (:export
   "PLANNING_CMD"
   "<PLANNING_CMD-REQUEST>"
   "PLANNING_CMD-REQUEST"
   "<PLANNING_CMD-RESPONSE>"
   "PLANNING_CMD-RESPONSE"
   "STRQUERYKDB"
   "<STRQUERYKDB-REQUEST>"
   "STRQUERYKDB-REQUEST"
   "<STRQUERYKDB-RESPONSE>"
   "STRQUERYKDB-RESPONSE"
   "INITKDB"
   "<INITKDB-REQUEST>"
   "INITKDB-REQUEST"
   "<INITKDB-RESPONSE>"
   "INITKDB-RESPONSE"
   "CLEARKDB"
   "<CLEARKDB-REQUEST>"
   "CLEARKDB-REQUEST"
   "<CLEARKDB-RESPONSE>"
   "CLEARKDB-RESPONSE"
  ))

