// Generated by gencpp from file simulator/Parameters.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_PARAMETERS_H
#define SIMULATOR_MESSAGE_PARAMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct Parameters_
{
  typedef Parameters_<ContainerAllocator> Type;

  Parameters_()
    : robot_x(0.0)
    , robot_y(0.0)
    , robot_theta(0.0)
    , robot_radio(0.0)
    , robot_max_advance(0.0)
    , robot_turn_angle(0.0)
    , laser_num_sensors(0)
    , laser_origin(0.0)
    , laser_range(0.0)
    , laser_value(0.0)
    , world_name()
    , noise(false)
    , run(false)
    , light_x(0.0)
    , light_y(0.0)
    , behavior(0)
    , steps(0)  {
    }
  Parameters_(const ContainerAllocator& _alloc)
    : robot_x(0.0)
    , robot_y(0.0)
    , robot_theta(0.0)
    , robot_radio(0.0)
    , robot_max_advance(0.0)
    , robot_turn_angle(0.0)
    , laser_num_sensors(0)
    , laser_origin(0.0)
    , laser_range(0.0)
    , laser_value(0.0)
    , world_name(_alloc)
    , noise(false)
    , run(false)
    , light_x(0.0)
    , light_y(0.0)
    , behavior(0)
    , steps(0)  {
  (void)_alloc;
    }



   typedef float _robot_x_type;
  _robot_x_type robot_x;

   typedef float _robot_y_type;
  _robot_y_type robot_y;

   typedef float _robot_theta_type;
  _robot_theta_type robot_theta;

   typedef float _robot_radio_type;
  _robot_radio_type robot_radio;

   typedef float _robot_max_advance_type;
  _robot_max_advance_type robot_max_advance;

   typedef float _robot_turn_angle_type;
  _robot_turn_angle_type robot_turn_angle;

   typedef int32_t _laser_num_sensors_type;
  _laser_num_sensors_type laser_num_sensors;

   typedef float _laser_origin_type;
  _laser_origin_type laser_origin;

   typedef float _laser_range_type;
  _laser_range_type laser_range;

   typedef float _laser_value_type;
  _laser_value_type laser_value;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _world_name_type;
  _world_name_type world_name;

   typedef uint8_t _noise_type;
  _noise_type noise;

   typedef uint8_t _run_type;
  _run_type run;

   typedef float _light_x_type;
  _light_x_type light_x;

   typedef float _light_y_type;
  _light_y_type light_y;

   typedef int32_t _behavior_type;
  _behavior_type behavior;

   typedef int32_t _steps_type;
  _steps_type steps;




  typedef boost::shared_ptr< ::simulator::Parameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::Parameters_<ContainerAllocator> const> ConstPtr;

}; // struct Parameters_

typedef ::simulator::Parameters_<std::allocator<void> > Parameters;

typedef boost::shared_ptr< ::simulator::Parameters > ParametersPtr;
typedef boost::shared_ptr< ::simulator::Parameters const> ParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::Parameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::Parameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'simulator': ['/home/diego/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::Parameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::Parameters_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::Parameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::Parameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::Parameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::Parameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::Parameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3a3242b503b35f6fa2f7b2245605401";
  }

  static const char* value(const ::simulator::Parameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3a3242b503b35f6ULL;
  static const uint64_t static_value2 = 0xfa2f7b2245605401ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::Parameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/Parameters";
  }

  static const char* value(const ::simulator::Parameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::Parameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 robot_x\n\
float32 robot_y\n\
float32 robot_theta\n\
float32 robot_radio\n\
float32 robot_max_advance\n\
float32 robot_turn_angle\n\
int32 laser_num_sensors\n\
float32 laser_origin\n\
float32 laser_range\n\
float32 laser_value\n\
string world_name\n\
bool noise\n\
bool run\n\
float32 light_x\n\
float32 light_y\n\
int32 behavior\n\
int32 steps\n\
";
  }

  static const char* value(const ::simulator::Parameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::Parameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_x);
      stream.next(m.robot_y);
      stream.next(m.robot_theta);
      stream.next(m.robot_radio);
      stream.next(m.robot_max_advance);
      stream.next(m.robot_turn_angle);
      stream.next(m.laser_num_sensors);
      stream.next(m.laser_origin);
      stream.next(m.laser_range);
      stream.next(m.laser_value);
      stream.next(m.world_name);
      stream.next(m.noise);
      stream.next(m.run);
      stream.next(m.light_x);
      stream.next(m.light_y);
      stream.next(m.behavior);
      stream.next(m.steps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Parameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::Parameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::Parameters_<ContainerAllocator>& v)
  {
    s << indent << "robot_x: ";
    Printer<float>::stream(s, indent + "  ", v.robot_x);
    s << indent << "robot_y: ";
    Printer<float>::stream(s, indent + "  ", v.robot_y);
    s << indent << "robot_theta: ";
    Printer<float>::stream(s, indent + "  ", v.robot_theta);
    s << indent << "robot_radio: ";
    Printer<float>::stream(s, indent + "  ", v.robot_radio);
    s << indent << "robot_max_advance: ";
    Printer<float>::stream(s, indent + "  ", v.robot_max_advance);
    s << indent << "robot_turn_angle: ";
    Printer<float>::stream(s, indent + "  ", v.robot_turn_angle);
    s << indent << "laser_num_sensors: ";
    Printer<int32_t>::stream(s, indent + "  ", v.laser_num_sensors);
    s << indent << "laser_origin: ";
    Printer<float>::stream(s, indent + "  ", v.laser_origin);
    s << indent << "laser_range: ";
    Printer<float>::stream(s, indent + "  ", v.laser_range);
    s << indent << "laser_value: ";
    Printer<float>::stream(s, indent + "  ", v.laser_value);
    s << indent << "world_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.world_name);
    s << indent << "noise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.noise);
    s << indent << "run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run);
    s << indent << "light_x: ";
    Printer<float>::stream(s, indent + "  ", v.light_x);
    s << indent << "light_y: ";
    Printer<float>::stream(s, indent + "  ", v.light_y);
    s << indent << "behavior: ";
    Printer<int32_t>::stream(s, indent + "  ", v.behavior);
    s << indent << "steps: ";
    Printer<int32_t>::stream(s, indent + "  ", v.steps);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_PARAMETERS_H
