// Generated by gencpp from file simulator/simulator_lightResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LIGHTRESPONSE_H
#define SIMULATOR_MESSAGE_SIMULATOR_LIGHTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_lightResponse_
{
  typedef simulator_lightResponse_<ContainerAllocator> Type;

  simulator_lightResponse_()
    : values()  {
      values.assign(0.0);
  }
  simulator_lightResponse_(const ContainerAllocator& _alloc)
    : values()  {
  (void)_alloc;
      values.assign(0.0);
  }



   typedef boost::array<float, 8>  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::simulator::simulator_lightResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_lightResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_lightResponse_

typedef ::simulator::simulator_lightResponse_<std::allocator<void> > simulator_lightResponse;

typedef boost::shared_ptr< ::simulator::simulator_lightResponse > simulator_lightResponsePtr;
typedef boost::shared_ptr< ::simulator::simulator_lightResponse const> simulator_lightResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_lightResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_lightResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'simulator': ['/home/diego/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_lightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_lightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_lightResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_lightResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_lightResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_lightResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_lightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14066f48a82f2883da023bd184c3f4ce";
  }

  static const char* value(const ::simulator::simulator_lightResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14066f48a82f2883ULL;
  static const uint64_t static_value2 = 0xda023bd184c3f4ceULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_lightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_lightResponse";
  }

  static const char* value(const ::simulator::simulator_lightResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_lightResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[8] values\n\
\n\
";
  }

  static const char* value(const ::simulator::simulator_lightResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_lightResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_lightResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_lightResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_lightResponse_<ContainerAllocator>& v)
  {
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LIGHTRESPONSE_H
