// Generated by gencpp from file simulator/simulator_turtlebot.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_TURTLEBOT_H
#define SIMULATOR_MESSAGE_SIMULATOR_TURTLEBOT_H

#include <ros/service_traits.h>


#include <simulator/simulator_turtlebotRequest.h>
#include <simulator/simulator_turtlebotResponse.h>


namespace simulator
{

struct simulator_turtlebot
{

typedef simulator_turtlebotRequest Request;
typedef simulator_turtlebotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simulator_turtlebot
} // namespace simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulator::simulator_turtlebot > {
  static const char* value()
  {
    return "f6c91c9ac3aa81fb2b1334bdb82aee4d";
  }

  static const char* value(const ::simulator::simulator_turtlebot&) { return value(); }
};

template<>
struct DataType< ::simulator::simulator_turtlebot > {
  static const char* value()
  {
    return "simulator/simulator_turtlebot";
  }

  static const char* value(const ::simulator::simulator_turtlebot&) { return value(); }
};


// service_traits::MD5Sum< ::simulator::simulator_turtlebotRequest> should match 
// service_traits::MD5Sum< ::simulator::simulator_turtlebot > 
template<>
struct MD5Sum< ::simulator::simulator_turtlebotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_turtlebot >::value();
  }
  static const char* value(const ::simulator::simulator_turtlebotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_turtlebotRequest> should match 
// service_traits::DataType< ::simulator::simulator_turtlebot > 
template<>
struct DataType< ::simulator::simulator_turtlebotRequest>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_turtlebot >::value();
  }
  static const char* value(const ::simulator::simulator_turtlebotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulator::simulator_turtlebotResponse> should match 
// service_traits::MD5Sum< ::simulator::simulator_turtlebot > 
template<>
struct MD5Sum< ::simulator::simulator_turtlebotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_turtlebot >::value();
  }
  static const char* value(const ::simulator::simulator_turtlebotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_turtlebotResponse> should match 
// service_traits::DataType< ::simulator::simulator_turtlebot > 
template<>
struct DataType< ::simulator::simulator_turtlebotResponse>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_turtlebot >::value();
  }
  static const char* value(const ::simulator::simulator_turtlebotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_TURTLEBOT_H
