// Generated by gencpp from file simulator/simulator_robot_stepResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ROBOT_STEPRESPONSE_H
#define SIMULATOR_MESSAGE_SIMULATOR_ROBOT_STEPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_robot_stepResponse_
{
  typedef simulator_robot_stepResponse_<ContainerAllocator> Type;

  simulator_robot_stepResponse_()
    : success(0)
    , robot_x(0.0)
    , robot_y(0.0)
    , theta(0.0)  {
    }
  simulator_robot_stepResponse_(const ContainerAllocator& _alloc)
    : success(0)
    , robot_x(0.0)
    , robot_y(0.0)
    , theta(0.0)  {
  (void)_alloc;
    }



   typedef int64_t _success_type;
  _success_type success;

   typedef float _robot_x_type;
  _robot_x_type robot_x;

   typedef float _robot_y_type;
  _robot_y_type robot_y;

   typedef float _theta_type;
  _theta_type theta;




  typedef boost::shared_ptr< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_robot_stepResponse_

typedef ::simulator::simulator_robot_stepResponse_<std::allocator<void> > simulator_robot_stepResponse;

typedef boost::shared_ptr< ::simulator::simulator_robot_stepResponse > simulator_robot_stepResponsePtr;
typedef boost::shared_ptr< ::simulator::simulator_robot_stepResponse const> simulator_robot_stepResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_robot_stepResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b14c95024f78daedb38b11b4fec62303";
  }

  static const char* value(const ::simulator::simulator_robot_stepResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb14c95024f78daedULL;
  static const uint64_t static_value2 = 0xb38b11b4fec62303ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_robot_stepResponse";
  }

  static const char* value(const ::simulator::simulator_robot_stepResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 success\n\
float32 robot_x\n\
float32 robot_y\n\
float32 theta\n\
\n\
";
  }

  static const char* value(const ::simulator::simulator_robot_stepResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.robot_x);
      stream.next(m.robot_y);
      stream.next(m.theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_robot_stepResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_robot_stepResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_robot_stepResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int64_t>::stream(s, indent + "  ", v.success);
    s << indent << "robot_x: ";
    Printer<float>::stream(s, indent + "  ", v.robot_x);
    s << indent << "robot_y: ";
    Printer<float>::stream(s, indent + "  ", v.robot_y);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ROBOT_STEPRESPONSE_H
