// Generated by gencpp from file simulator/simulator_laserRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LASERREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_LASERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_laserRequest_
{
  typedef simulator_laserRequest_<ContainerAllocator> Type;

  simulator_laserRequest_()
    : robot_x(0.0)
    , robot_y(0.0)
    , robot_theta(0.0)  {
    }
  simulator_laserRequest_(const ContainerAllocator& _alloc)
    : robot_x(0.0)
    , robot_y(0.0)
    , robot_theta(0.0)  {
  (void)_alloc;
    }



   typedef float _robot_x_type;
  _robot_x_type robot_x;

   typedef float _robot_y_type;
  _robot_y_type robot_y;

   typedef float _robot_theta_type;
  _robot_theta_type robot_theta;




  typedef boost::shared_ptr< ::simulator::simulator_laserRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_laserRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_laserRequest_

typedef ::simulator::simulator_laserRequest_<std::allocator<void> > simulator_laserRequest;

typedef boost::shared_ptr< ::simulator::simulator_laserRequest > simulator_laserRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_laserRequest const> simulator_laserRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_laserRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_laserRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'simulator': ['/home/diego/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_laserRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_laserRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_laserRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b5912b3f7415e4bfa50e61e9c2f4a793";
  }

  static const char* value(const ::simulator::simulator_laserRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb5912b3f7415e4bfULL;
  static const uint64_t static_value2 = 0xa50e61e9c2f4a793ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_laserRequest";
  }

  static const char* value(const ::simulator::simulator_laserRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 robot_x\n\
float32 robot_y\n\
float32 robot_theta\n\
";
  }

  static const char* value(const ::simulator::simulator_laserRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_laserRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_x);
      stream.next(m.robot_y);
      stream.next(m.robot_theta);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_laserRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_laserRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_laserRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_x: ";
    Printer<float>::stream(s, indent + "  ", v.robot_x);
    s << indent << "robot_y: ";
    Printer<float>::stream(s, indent + "  ", v.robot_y);
    s << indent << "robot_theta: ";
    Printer<float>::stream(s, indent + "  ", v.robot_theta);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LASERREQUEST_H
