// Generated by gencpp from file simulator/simulator_laserResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LASERRESPONSE_H
#define SIMULATOR_MESSAGE_SIMULATOR_LASERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_laserResponse_
{
  typedef simulator_laserResponse_<ContainerAllocator> Type;

  simulator_laserResponse_()
    : sensors()  {
      sensors.assign(0.0);
  }
  simulator_laserResponse_(const ContainerAllocator& _alloc)
    : sensors()  {
  (void)_alloc;
      sensors.assign(0.0);
  }



   typedef boost::array<float, 1024>  _sensors_type;
  _sensors_type sensors;




  typedef boost::shared_ptr< ::simulator::simulator_laserResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_laserResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_laserResponse_

typedef ::simulator::simulator_laserResponse_<std::allocator<void> > simulator_laserResponse;

typedef boost::shared_ptr< ::simulator::simulator_laserResponse > simulator_laserResponsePtr;
typedef boost::shared_ptr< ::simulator::simulator_laserResponse const> simulator_laserResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_laserResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_laserResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'simulator': ['/home/diego/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_laserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_laserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_laserResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_laserResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_laserResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_laserResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_laserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b7c66021a50d0b84ad4cd13e2a7a878b";
  }

  static const char* value(const ::simulator::simulator_laserResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb7c66021a50d0b84ULL;
  static const uint64_t static_value2 = 0xad4cd13e2a7a878bULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_laserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_laserResponse";
  }

  static const char* value(const ::simulator::simulator_laserResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_laserResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[1024] sensors\n\
\n\
";
  }

  static const char* value(const ::simulator::simulator_laserResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_laserResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sensors);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_laserResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_laserResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_laserResponse_<ContainerAllocator>& v)
  {
    s << indent << "sensors[]" << std::endl;
    for (size_t i = 0; i < v.sensors.size(); ++i)
    {
      s << indent << "  sensors[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sensors[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LASERRESPONSE_H
