// Generated by gencpp from file simulator/simulator_turtlebotResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_TURTLEBOTRESPONSE_H
#define SIMULATOR_MESSAGE_SIMULATOR_TURTLEBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_turtlebotResponse_
{
  typedef simulator_turtlebotResponse_<ContainerAllocator> Type;

  simulator_turtlebotResponse_()
    : done(0.0)  {
    }
  simulator_turtlebotResponse_(const ContainerAllocator& _alloc)
    : done(0.0)  {
  (void)_alloc;
    }



   typedef float _done_type;
  _done_type done;




  typedef boost::shared_ptr< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_turtlebotResponse_

typedef ::simulator::simulator_turtlebotResponse_<std::allocator<void> > simulator_turtlebotResponse;

typedef boost::shared_ptr< ::simulator::simulator_turtlebotResponse > simulator_turtlebotResponsePtr;
typedef boost::shared_ptr< ::simulator::simulator_turtlebotResponse const> simulator_turtlebotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_turtlebotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c6a688b7fb35639b2b6480a10592731";
  }

  static const char* value(const ::simulator::simulator_turtlebotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c6a688b7fb35639ULL;
  static const uint64_t static_value2 = 0xb2b6480a10592731ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_turtlebotResponse";
  }

  static const char* value(const ::simulator::simulator_turtlebotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 done\n\
";
  }

  static const char* value(const ::simulator::simulator_turtlebotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.done);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_turtlebotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_turtlebotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_turtlebotResponse_<ContainerAllocator>& v)
  {
    s << indent << "done: ";
    Printer<float>::stream(s, indent + "  ", v.done);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_TURTLEBOTRESPONSE_H
