// Generated by gencpp from file simulator/simulator_robot_laser_valuesResponse.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ROBOT_LASER_VALUESRESPONSE_H
#define SIMULATOR_MESSAGE_SIMULATOR_ROBOT_LASER_VALUESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_robot_laser_valuesResponse_
{
  typedef simulator_robot_laser_valuesResponse_<ContainerAllocator> Type;

  simulator_robot_laser_valuesResponse_()
    : success(0)  {
    }
  simulator_robot_laser_valuesResponse_(const ContainerAllocator& _alloc)
    : success(0)  {
  (void)_alloc;
    }



   typedef int64_t _success_type;
  _success_type success;




  typedef boost::shared_ptr< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_robot_laser_valuesResponse_

typedef ::simulator::simulator_robot_laser_valuesResponse_<std::allocator<void> > simulator_robot_laser_valuesResponse;

typedef boost::shared_ptr< ::simulator::simulator_robot_laser_valuesResponse > simulator_robot_laser_valuesResponsePtr;
typedef boost::shared_ptr< ::simulator::simulator_robot_laser_valuesResponse const> simulator_robot_laser_valuesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f26af2399fbfbc8170d9a60ed7b9846";
  }

  static const char* value(const ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f26af2399fbfbc8ULL;
  static const uint64_t static_value2 = 0x170d9a60ed7b9846ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_robot_laser_valuesResponse";
  }

  static const char* value(const ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 success\n\
";
  }

  static const char* value(const ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_robot_laser_valuesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_robot_laser_valuesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<int64_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ROBOT_LASER_VALUESRESPONSE_H
