// Generated by gencpp from file simulator/simulator_lightRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LIGHTREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_LIGHTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_lightRequest_
{
  typedef simulator_lightRequest_<ContainerAllocator> Type;

  simulator_lightRequest_()
    : req(0)  {
    }
  simulator_lightRequest_(const ContainerAllocator& _alloc)
    : req(0)  {
  (void)_alloc;
    }



   typedef int32_t _req_type;
  _req_type req;




  typedef boost::shared_ptr< ::simulator::simulator_lightRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_lightRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_lightRequest_

typedef ::simulator::simulator_lightRequest_<std::allocator<void> > simulator_lightRequest;

typedef boost::shared_ptr< ::simulator::simulator_lightRequest > simulator_lightRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_lightRequest const> simulator_lightRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_lightRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_lightRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'simulator': ['/home/diego/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_lightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_lightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_lightRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_lightRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_lightRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_lightRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_lightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "688ec893d5ff2cccc11b9bc8bc41109b";
  }

  static const char* value(const ::simulator::simulator_lightRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x688ec893d5ff2cccULL;
  static const uint64_t static_value2 = 0xc11b9bc8bc41109bULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_lightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_lightRequest";
  }

  static const char* value(const ::simulator::simulator_lightRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_lightRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 req\n\
";
  }

  static const char* value(const ::simulator::simulator_lightRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_lightRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.req);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_lightRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_lightRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_lightRequest_<ContainerAllocator>& v)
  {
    s << indent << "req: ";
    Printer<int32_t>::stream(s, indent + "  ", v.req);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LIGHTREQUEST_H
