// Generated by gencpp from file simulator/simulator_object_interactionRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_OBJECT_INTERACTIONREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_OBJECT_INTERACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_object_interactionRequest_
{
  typedef simulator_object_interactionRequest_<ContainerAllocator> Type;

  simulator_object_interactionRequest_()
    : grasp(0)
    , name()  {
    }
  simulator_object_interactionRequest_(const ContainerAllocator& _alloc)
    : grasp(0)
    , name(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _grasp_type;
  _grasp_type grasp;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;




  typedef boost::shared_ptr< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_object_interactionRequest_

typedef ::simulator::simulator_object_interactionRequest_<std::allocator<void> > simulator_object_interactionRequest;

typedef boost::shared_ptr< ::simulator::simulator_object_interactionRequest > simulator_object_interactionRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_object_interactionRequest const> simulator_object_interactionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_object_interactionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bcf10529fb49499b219a0783814b595a";
  }

  static const char* value(const ::simulator::simulator_object_interactionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbcf10529fb49499bULL;
  static const uint64_t static_value2 = 0x219a0783814b595aULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_object_interactionRequest";
  }

  static const char* value(const ::simulator::simulator_object_interactionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 grasp\n\
string name\n\
";
  }

  static const char* value(const ::simulator::simulator_object_interactionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.grasp);
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_object_interactionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_object_interactionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_object_interactionRequest_<ContainerAllocator>& v)
  {
    s << indent << "grasp: ";
    Printer<int32_t>::stream(s, indent + "  ", v.grasp);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_OBJECT_INTERACTIONREQUEST_H
