// Generated by gencpp from file simulator/simulator_laser.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LASER_H
#define SIMULATOR_MESSAGE_SIMULATOR_LASER_H

#include <ros/service_traits.h>


#include <simulator/simulator_laserRequest.h>
#include <simulator/simulator_laserResponse.h>


namespace simulator
{

struct simulator_laser
{

typedef simulator_laserRequest Request;
typedef simulator_laserResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simulator_laser
} // namespace simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulator::simulator_laser > {
  static const char* value()
  {
    return "d1e42417fddd5b94b1b79a5297e533e5";
  }

  static const char* value(const ::simulator::simulator_laser&) { return value(); }
};

template<>
struct DataType< ::simulator::simulator_laser > {
  static const char* value()
  {
    return "simulator/simulator_laser";
  }

  static const char* value(const ::simulator::simulator_laser&) { return value(); }
};


// service_traits::MD5Sum< ::simulator::simulator_laserRequest> should match 
// service_traits::MD5Sum< ::simulator::simulator_laser > 
template<>
struct MD5Sum< ::simulator::simulator_laserRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_laser >::value();
  }
  static const char* value(const ::simulator::simulator_laserRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_laserRequest> should match 
// service_traits::DataType< ::simulator::simulator_laser > 
template<>
struct DataType< ::simulator::simulator_laserRequest>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_laser >::value();
  }
  static const char* value(const ::simulator::simulator_laserRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulator::simulator_laserResponse> should match 
// service_traits::MD5Sum< ::simulator::simulator_laser > 
template<>
struct MD5Sum< ::simulator::simulator_laserResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_laser >::value();
  }
  static const char* value(const ::simulator::simulator_laserResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_laserResponse> should match 
// service_traits::DataType< ::simulator::simulator_laser > 
template<>
struct DataType< ::simulator::simulator_laserResponse>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_laser >::value();
  }
  static const char* value(const ::simulator::simulator_laserResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LASER_H
