// Generated by gencpp from file simulator/simulator_robot_laser_values.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ROBOT_LASER_VALUES_H
#define SIMULATOR_MESSAGE_SIMULATOR_ROBOT_LASER_VALUES_H

#include <ros/service_traits.h>


#include <simulator/simulator_robot_laser_valuesRequest.h>
#include <simulator/simulator_robot_laser_valuesResponse.h>


namespace simulator
{

struct simulator_robot_laser_values
{

typedef simulator_robot_laser_valuesRequest Request;
typedef simulator_robot_laser_valuesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simulator_robot_laser_values
} // namespace simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulator::simulator_robot_laser_values > {
  static const char* value()
  {
    return "7613cd23d5b6d8557cd0bb7c15272cc6";
  }

  static const char* value(const ::simulator::simulator_robot_laser_values&) { return value(); }
};

template<>
struct DataType< ::simulator::simulator_robot_laser_values > {
  static const char* value()
  {
    return "simulator/simulator_robot_laser_values";
  }

  static const char* value(const ::simulator::simulator_robot_laser_values&) { return value(); }
};


// service_traits::MD5Sum< ::simulator::simulator_robot_laser_valuesRequest> should match 
// service_traits::MD5Sum< ::simulator::simulator_robot_laser_values > 
template<>
struct MD5Sum< ::simulator::simulator_robot_laser_valuesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_robot_laser_values >::value();
  }
  static const char* value(const ::simulator::simulator_robot_laser_valuesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_robot_laser_valuesRequest> should match 
// service_traits::DataType< ::simulator::simulator_robot_laser_values > 
template<>
struct DataType< ::simulator::simulator_robot_laser_valuesRequest>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_robot_laser_values >::value();
  }
  static const char* value(const ::simulator::simulator_robot_laser_valuesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulator::simulator_robot_laser_valuesResponse> should match 
// service_traits::MD5Sum< ::simulator::simulator_robot_laser_values > 
template<>
struct MD5Sum< ::simulator::simulator_robot_laser_valuesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_robot_laser_values >::value();
  }
  static const char* value(const ::simulator::simulator_robot_laser_valuesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_robot_laser_valuesResponse> should match 
// service_traits::DataType< ::simulator::simulator_robot_laser_values > 
template<>
struct DataType< ::simulator::simulator_robot_laser_valuesResponse>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_robot_laser_values >::value();
  }
  static const char* value(const ::simulator::simulator_robot_laser_valuesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ROBOT_LASER_VALUES_H
