// Generated by gencpp from file simulator/simulator_robot_stepRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ROBOT_STEPREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_ROBOT_STEPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_robot_stepRequest_
{
  typedef simulator_robot_stepRequest_<ContainerAllocator> Type;

  simulator_robot_stepRequest_()
    : theta(0.0)
    , distance(0.0)
    , sensors()
    , stop(false)  {
      sensors.assign(0.0);
  }
  simulator_robot_stepRequest_(const ContainerAllocator& _alloc)
    : theta(0.0)
    , distance(0.0)
    , sensors()
    , stop(false)  {
  (void)_alloc;
      sensors.assign(0.0);
  }



   typedef float _theta_type;
  _theta_type theta;

   typedef float _distance_type;
  _distance_type distance;

   typedef boost::array<float, 512>  _sensors_type;
  _sensors_type sensors;

   typedef uint8_t _stop_type;
  _stop_type stop;




  typedef boost::shared_ptr< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_robot_stepRequest_

typedef ::simulator::simulator_robot_stepRequest_<std::allocator<void> > simulator_robot_stepRequest;

typedef boost::shared_ptr< ::simulator::simulator_robot_stepRequest > simulator_robot_stepRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_robot_stepRequest const> simulator_robot_stepRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_robot_stepRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55fcd6c1882b7be6df8bd89be472cdeb";
  }

  static const char* value(const ::simulator::simulator_robot_stepRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55fcd6c1882b7be6ULL;
  static const uint64_t static_value2 = 0xdf8bd89be472cdebULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_robot_stepRequest";
  }

  static const char* value(const ::simulator::simulator_robot_stepRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta\n\
float32 distance\n\
float32[512] sensors\n\
bool stop\n\
";
  }

  static const char* value(const ::simulator::simulator_robot_stepRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta);
      stream.next(m.distance);
      stream.next(m.sensors);
      stream.next(m.stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_robot_stepRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_robot_stepRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_robot_stepRequest_<ContainerAllocator>& v)
  {
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "sensors[]" << std::endl;
    for (size_t i = 0; i < v.sensors.size(); ++i)
    {
      s << indent << "  sensors[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.sensors[i]);
    }
    s << indent << "stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ROBOT_STEPREQUEST_H
