// Generated by gencpp from file simulator/simulator_algorithm_resultRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_ALGORITHM_RESULTREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_ALGORITHM_RESULTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_algorithm_resultRequest_
{
  typedef simulator_algorithm_resultRequest_<ContainerAllocator> Type;

  simulator_algorithm_resultRequest_()
    : nodes_algorithm()
    , num_nodos(0)  {
      nodes_algorithm.assign(0);
  }
  simulator_algorithm_resultRequest_(const ContainerAllocator& _alloc)
    : nodes_algorithm()
    , num_nodos(0)  {
  (void)_alloc;
      nodes_algorithm.assign(0);
  }



   typedef boost::array<int32_t, 200>  _nodes_algorithm_type;
  _nodes_algorithm_type nodes_algorithm;

   typedef int32_t _num_nodos_type;
  _num_nodos_type num_nodos;




  typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_algorithm_resultRequest_

typedef ::simulator::simulator_algorithm_resultRequest_<std::allocator<void> > simulator_algorithm_resultRequest;

typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultRequest > simulator_algorithm_resultRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_algorithm_resultRequest const> simulator_algorithm_resultRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f9bf1c621c94a08bbe9f7fd16b22915";
  }

  static const char* value(const ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f9bf1c621c94a08ULL;
  static const uint64_t static_value2 = 0xbbe9f7fd16b22915ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_algorithm_resultRequest";
  }

  static const char* value(const ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[200] nodes_algorithm\n\
int32 num_nodos\n\
";
  }

  static const char* value(const ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.nodes_algorithm);
      stream.next(m.num_nodos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_algorithm_resultRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_algorithm_resultRequest_<ContainerAllocator>& v)
  {
    s << indent << "nodes_algorithm[]" << std::endl;
    for (size_t i = 0; i < v.nodes_algorithm.size(); ++i)
    {
      s << indent << "  nodes_algorithm[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.nodes_algorithm[i]);
    }
    s << indent << "num_nodos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_nodos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_ALGORITHM_RESULTREQUEST_H
