// Generated by gencpp from file simulator/simulator_set_light_positionRequest.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_SET_LIGHT_POSITIONREQUEST_H
#define SIMULATOR_MESSAGE_SIMULATOR_SET_LIGHT_POSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace simulator
{
template <class ContainerAllocator>
struct simulator_set_light_positionRequest_
{
  typedef simulator_set_light_positionRequest_<ContainerAllocator> Type;

  simulator_set_light_positionRequest_()
    : light_x(0.0)
    , light_y(0.0)  {
    }
  simulator_set_light_positionRequest_(const ContainerAllocator& _alloc)
    : light_x(0.0)
    , light_y(0.0)  {
  (void)_alloc;
    }



   typedef float _light_x_type;
  _light_x_type light_x;

   typedef float _light_y_type;
  _light_y_type light_y;




  typedef boost::shared_ptr< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct simulator_set_light_positionRequest_

typedef ::simulator::simulator_set_light_positionRequest_<std::allocator<void> > simulator_set_light_positionRequest;

typedef boost::shared_ptr< ::simulator::simulator_set_light_positionRequest > simulator_set_light_positionRequestPtr;
typedef boost::shared_ptr< ::simulator::simulator_set_light_positionRequest const> simulator_set_light_positionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace simulator

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'simulator': ['/home/gerardo/catkin_ws/src/simulator/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0928589eca381ffd96f6bd262e71266";
  }

  static const char* value(const ::simulator::simulator_set_light_positionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0928589eca381ffULL;
  static const uint64_t static_value2 = 0xd96f6bd262e71266ULL;
};

template<class ContainerAllocator>
struct DataType< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "simulator/simulator_set_light_positionRequest";
  }

  static const char* value(const ::simulator::simulator_set_light_positionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 light_x\n\
float32 light_y\n\
";
  }

  static const char* value(const ::simulator::simulator_set_light_positionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.light_x);
      stream.next(m.light_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct simulator_set_light_positionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::simulator::simulator_set_light_positionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::simulator::simulator_set_light_positionRequest_<ContainerAllocator>& v)
  {
    s << indent << "light_x: ";
    Printer<float>::stream(s, indent + "  ", v.light_x);
    s << indent << "light_y: ";
    Printer<float>::stream(s, indent + "  ", v.light_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_SET_LIGHT_POSITIONREQUEST_H
