// Generated by gencpp from file clips_ros/InitKDBRequest.msg
// DO NOT EDIT!


#ifndef CLIPS_ROS_MESSAGE_INITKDBREQUEST_H
#define CLIPS_ROS_MESSAGE_INITKDBREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace clips_ros
{
template <class ContainerAllocator>
struct InitKDBRequest_
{
  typedef InitKDBRequest_<ContainerAllocator> Type;

  InitKDBRequest_()
    : filePath()
    , run(false)  {
    }
  InitKDBRequest_(const ContainerAllocator& _alloc)
    : filePath(_alloc)
    , run(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _filePath_type;
  _filePath_type filePath;

   typedef uint8_t _run_type;
  _run_type run;




  typedef boost::shared_ptr< ::clips_ros::InitKDBRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::clips_ros::InitKDBRequest_<ContainerAllocator> const> ConstPtr;

}; // struct InitKDBRequest_

typedef ::clips_ros::InitKDBRequest_<std::allocator<void> > InitKDBRequest;

typedef boost::shared_ptr< ::clips_ros::InitKDBRequest > InitKDBRequestPtr;
typedef boost::shared_ptr< ::clips_ros::InitKDBRequest const> InitKDBRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::clips_ros::InitKDBRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::clips_ros::InitKDBRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace clips_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'clips_ros': ['/home/gerardo/catkin_ws/src/clips_ros/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::clips_ros::InitKDBRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::clips_ros::InitKDBRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::clips_ros::InitKDBRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d40ee22877bfab4f2e1de8cb2e7b970";
  }

  static const char* value(const ::clips_ros::InitKDBRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d40ee22877bfab4ULL;
  static const uint64_t static_value2 = 0xf2e1de8cb2e7b970ULL;
};

template<class ContainerAllocator>
struct DataType< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "clips_ros/InitKDBRequest";
  }

  static const char* value(const ::clips_ros::InitKDBRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string filePath\n\
bool run\n\
";
  }

  static const char* value(const ::clips_ros::InitKDBRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.filePath);
      stream.next(m.run);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct InitKDBRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::clips_ros::InitKDBRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::clips_ros::InitKDBRequest_<ContainerAllocator>& v)
  {
    s << indent << "filePath: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.filePath);
    s << indent << "run: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.run);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CLIPS_ROS_MESSAGE_INITKDBREQUEST_H
