// Generated by gencpp from file clips_ros/InitKDB.msg
// DO NOT EDIT!


#ifndef CLIPS_ROS_MESSAGE_INITKDB_H
#define CLIPS_ROS_MESSAGE_INITKDB_H

#include <ros/service_traits.h>


#include <clips_ros/InitKDBRequest.h>
#include <clips_ros/InitKDBResponse.h>


namespace clips_ros
{

struct InitKDB
{

typedef InitKDBRequest Request;
typedef InitKDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct InitKDB
} // namespace clips_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clips_ros::InitKDB > {
  static const char* value()
  {
    return "7d40ee22877bfab4f2e1de8cb2e7b970";
  }

  static const char* value(const ::clips_ros::InitKDB&) { return value(); }
};

template<>
struct DataType< ::clips_ros::InitKDB > {
  static const char* value()
  {
    return "clips_ros/InitKDB";
  }

  static const char* value(const ::clips_ros::InitKDB&) { return value(); }
};


// service_traits::MD5Sum< ::clips_ros::InitKDBRequest> should match 
// service_traits::MD5Sum< ::clips_ros::InitKDB > 
template<>
struct MD5Sum< ::clips_ros::InitKDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clips_ros::InitKDB >::value();
  }
  static const char* value(const ::clips_ros::InitKDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clips_ros::InitKDBRequest> should match 
// service_traits::DataType< ::clips_ros::InitKDB > 
template<>
struct DataType< ::clips_ros::InitKDBRequest>
{
  static const char* value()
  {
    return DataType< ::clips_ros::InitKDB >::value();
  }
  static const char* value(const ::clips_ros::InitKDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clips_ros::InitKDBResponse> should match 
// service_traits::MD5Sum< ::clips_ros::InitKDB > 
template<>
struct MD5Sum< ::clips_ros::InitKDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clips_ros::InitKDB >::value();
  }
  static const char* value(const ::clips_ros::InitKDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clips_ros::InitKDBResponse> should match 
// service_traits::DataType< ::clips_ros::InitKDB > 
template<>
struct DataType< ::clips_ros::InitKDBResponse>
{
  static const char* value()
  {
    return DataType< ::clips_ros::InitKDB >::value();
  }
  static const char* value(const ::clips_ros::InitKDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIPS_ROS_MESSAGE_INITKDB_H
