// Generated by gencpp from file clips_ros/planning_cmd.msg
// DO NOT EDIT!


#ifndef CLIPS_ROS_MESSAGE_PLANNING_CMD_H
#define CLIPS_ROS_MESSAGE_PLANNING_CMD_H

#include <ros/service_traits.h>


#include <clips_ros/planning_cmdRequest.h>
#include <clips_ros/planning_cmdResponse.h>


namespace clips_ros
{

struct planning_cmd
{

typedef planning_cmdRequest Request;
typedef planning_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct planning_cmd
} // namespace clips_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clips_ros::planning_cmd > {
  static const char* value()
  {
    return "f9f6635257061aef8bea97260f4e6a8b";
  }

  static const char* value(const ::clips_ros::planning_cmd&) { return value(); }
};

template<>
struct DataType< ::clips_ros::planning_cmd > {
  static const char* value()
  {
    return "clips_ros/planning_cmd";
  }

  static const char* value(const ::clips_ros::planning_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::clips_ros::planning_cmdRequest> should match 
// service_traits::MD5Sum< ::clips_ros::planning_cmd > 
template<>
struct MD5Sum< ::clips_ros::planning_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clips_ros::planning_cmd >::value();
  }
  static const char* value(const ::clips_ros::planning_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clips_ros::planning_cmdRequest> should match 
// service_traits::DataType< ::clips_ros::planning_cmd > 
template<>
struct DataType< ::clips_ros::planning_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::clips_ros::planning_cmd >::value();
  }
  static const char* value(const ::clips_ros::planning_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clips_ros::planning_cmdResponse> should match 
// service_traits::MD5Sum< ::clips_ros::planning_cmd > 
template<>
struct MD5Sum< ::clips_ros::planning_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clips_ros::planning_cmd >::value();
  }
  static const char* value(const ::clips_ros::planning_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clips_ros::planning_cmdResponse> should match 
// service_traits::DataType< ::clips_ros::planning_cmd > 
template<>
struct DataType< ::clips_ros::planning_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::clips_ros::planning_cmd >::value();
  }
  static const char* value(const ::clips_ros::planning_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIPS_ROS_MESSAGE_PLANNING_CMD_H
