// Generated by gencpp from file clips_ros/StrQueryKDB.msg
// DO NOT EDIT!


#ifndef CLIPS_ROS_MESSAGE_STRQUERYKDB_H
#define CLIPS_ROS_MESSAGE_STRQUERYKDB_H

#include <ros/service_traits.h>


#include <clips_ros/StrQueryKDBRequest.h>
#include <clips_ros/StrQueryKDBResponse.h>


namespace clips_ros
{

struct StrQueryKDB
{

typedef StrQueryKDBRequest Request;
typedef StrQueryKDBResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StrQueryKDB
} // namespace clips_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::clips_ros::StrQueryKDB > {
  static const char* value()
  {
    return "40ece397ad679f27203bff340007bd45";
  }

  static const char* value(const ::clips_ros::StrQueryKDB&) { return value(); }
};

template<>
struct DataType< ::clips_ros::StrQueryKDB > {
  static const char* value()
  {
    return "clips_ros/StrQueryKDB";
  }

  static const char* value(const ::clips_ros::StrQueryKDB&) { return value(); }
};


// service_traits::MD5Sum< ::clips_ros::StrQueryKDBRequest> should match 
// service_traits::MD5Sum< ::clips_ros::StrQueryKDB > 
template<>
struct MD5Sum< ::clips_ros::StrQueryKDBRequest>
{
  static const char* value()
  {
    return MD5Sum< ::clips_ros::StrQueryKDB >::value();
  }
  static const char* value(const ::clips_ros::StrQueryKDBRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::clips_ros::StrQueryKDBRequest> should match 
// service_traits::DataType< ::clips_ros::StrQueryKDB > 
template<>
struct DataType< ::clips_ros::StrQueryKDBRequest>
{
  static const char* value()
  {
    return DataType< ::clips_ros::StrQueryKDB >::value();
  }
  static const char* value(const ::clips_ros::StrQueryKDBRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::clips_ros::StrQueryKDBResponse> should match 
// service_traits::MD5Sum< ::clips_ros::StrQueryKDB > 
template<>
struct MD5Sum< ::clips_ros::StrQueryKDBResponse>
{
  static const char* value()
  {
    return MD5Sum< ::clips_ros::StrQueryKDB >::value();
  }
  static const char* value(const ::clips_ros::StrQueryKDBResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::clips_ros::StrQueryKDBResponse> should match 
// service_traits::DataType< ::clips_ros::StrQueryKDB > 
template<>
struct DataType< ::clips_ros::StrQueryKDBResponse>
{
  static const char* value()
  {
    return DataType< ::clips_ros::StrQueryKDB >::value();
  }
  static const char* value(const ::clips_ros::StrQueryKDBResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CLIPS_ROS_MESSAGE_STRQUERYKDB_H
