// Generated by gencpp from file simulator/simulator_light.msg
// DO NOT EDIT!


#ifndef SIMULATOR_MESSAGE_SIMULATOR_LIGHT_H
#define SIMULATOR_MESSAGE_SIMULATOR_LIGHT_H

#include <ros/service_traits.h>


#include <simulator/simulator_lightRequest.h>
#include <simulator/simulator_lightResponse.h>


namespace simulator
{

struct simulator_light
{

typedef simulator_lightRequest Request;
typedef simulator_lightResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct simulator_light
} // namespace simulator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::simulator::simulator_light > {
  static const char* value()
  {
    return "f0a363bdf6e9db5ed005776d88d3f68d";
  }

  static const char* value(const ::simulator::simulator_light&) { return value(); }
};

template<>
struct DataType< ::simulator::simulator_light > {
  static const char* value()
  {
    return "simulator/simulator_light";
  }

  static const char* value(const ::simulator::simulator_light&) { return value(); }
};


// service_traits::MD5Sum< ::simulator::simulator_lightRequest> should match 
// service_traits::MD5Sum< ::simulator::simulator_light > 
template<>
struct MD5Sum< ::simulator::simulator_lightRequest>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_light >::value();
  }
  static const char* value(const ::simulator::simulator_lightRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_lightRequest> should match 
// service_traits::DataType< ::simulator::simulator_light > 
template<>
struct DataType< ::simulator::simulator_lightRequest>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_light >::value();
  }
  static const char* value(const ::simulator::simulator_lightRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::simulator::simulator_lightResponse> should match 
// service_traits::MD5Sum< ::simulator::simulator_light > 
template<>
struct MD5Sum< ::simulator::simulator_lightResponse>
{
  static const char* value()
  {
    return MD5Sum< ::simulator::simulator_light >::value();
  }
  static const char* value(const ::simulator::simulator_lightResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::simulator::simulator_lightResponse> should match 
// service_traits::DataType< ::simulator::simulator_light > 
template<>
struct DataType< ::simulator::simulator_lightResponse>
{
  static const char* value()
  {
    return DataType< ::simulator::simulator_light >::value();
  }
  static const char* value(const ::simulator::simulator_lightResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SIMULATOR_MESSAGE_SIMULATOR_LIGHT_H
